name: Tests
on:
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      #fetch latest code version
      - name: Code
        uses: actions/checkout@v4
      - name: Install Node v20
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install
        run: npm install
      - name: Test
        run: npm run test